language: rust
sudo: false
cache: cargo

GH_TOKEN: &GH_TOKEN
  secure: Nn53efN4SdwxHgpDWUDdX+sBWkZM0OOM99+a1NgFvPmqaI0TZs7CfPDl1D9jJIhFWk087A15/O69BNfOxfRKE4CDZJHIdj2MW64xKM04oFxXbY4lKsLy5DxnuwF9w7tRL/qSieqIn+uY0gVoKmku80c0xMMMdS93QmqQUJb4QgxJcX4ZDPI5q1JZbJ3JLST1nRncobmzwqG6qBrpY/DY+V+Xr4x+C+hNARoCQbqRfx4RsuN0Svn5QN8E+7MIp8vBM96R28aCtg1+YtvJQGYaBqaHTtr9bQcXsEq1I1RaIZsEXaCjF6MUTz2KrFd5Iv5Fh7epALVYKK4ZA90379enKUlL4IcUCqPh7BcJmfwNPSHkDItkeezr54oquDnv+oV0ku84kpCLIq9k4yL/70efWYtDOT9utp1bD9EDi49pnv4cWI6r/wUZoxBj4OL0b4Oy8t+1l1VI5j6ey/DsbtK27zEi+upHdXu17cwrZ7QQP9QevKFmQdHkSkMNjk3+1Y1VV1HVw0SMxysqft03NiGrXo1HW76/lsVWRNk/fU1obSABHqFm670mBo150zGYEotGCeMA5QNSb+othVeExkKkQw2VCRnDaByqyFcrFo4YliU2FeVG1oq/tfs5m1uSdIWQ+ZXuVaCkMoOnzhp5vWEOs9kPR9pQ34tPY3foUsDcVSg=

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "Sam Goldman"
    - git config --local user.email "sgoldman216@gmail.com"
    - name="primitive_image-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/primitive_image $name/
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      strip $name/primitive_image;
      zip -r $name.zip $name;
      fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      zip -r $name.zip $name;
      fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      7z a $name.zip $name;
      fi
  deploy:
    provider: releases
    api_key: *GH_TOKEN
    file: primitive_image-$TRAVIS_TAG-$TARGET.zip
    skip_cleanup: true
    on:
      branch: master
      tags: true

jobs:
  include:

    - stage: Tests
      env: RUST_BACKTRACE=1
      rust: stable
      script:
        - cargo test --locked

    - stage: Build
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
      before_script: rustup target add $TARGET
      script: cargo build --release --target $TARGET --locked
      <<: *DEPLOY_TO_GITHUB

    - stage: Build
      env: TARGET=x86_64-apple-darwin
      os: osx
      rust: stable
      before_script: rustup target add $TARGET
      script: cargo build --release --target $TARGET --locked
      install: true
      <<: *DEPLOY_TO_GITHUB

    - name: Build
      env: TARGET=x86_64-pc-windows-msvc
      os: windows
      rust: stable
      before_script: rustup target add $TARGET
      script: cargo build --release --target $TARGET --locked
      <<: *DEPLOY_TO_GITHUB

notifications:
  email:
    on_success: never
